version: '3'
services:
  app:
    build:
        context: ./
    tty: true
    volumes:
        - ./slack_common_notice:/app/slack_common_notice
    working_dir: /app/slack_common_notice
    environment:
      - PYTHONPATH=/app